import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import { ServicesProvider } from "@/contexts/ServicesContext";
import { SurvivalModeProvider } from "@/features/ui/SurvivalModeContext";
import { GameProvider } from "@/contexts/GameContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Providers } from "@/components/Providers";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				suppressHydrationWarning
			>
				<Providers>
					<SurvivalModeProvider>
						<GameProvider>
							<ServicesProvider>{children}</ServicesProvider>
						</GameProvider>
					</SurvivalModeProvider>
				</Providers>
			</body>
		</html>
	);
}
